name: Send OTA update

on:
  push:
    branches: ['main']
    paths:
      - app/**
      - src/**
      - shared/**
      - assets/**
      - app.json
      - package.json
      - '!api/**'

jobs:
  send_update:
    name: Send OTA update to production
    type: update
    params:
      channel: production
